Importando dados, string vazia, string como factor
```{r}
data = read.csv("data/Churn.csv", sep = ";", na.strings="", stringsAsFactors=T)
head(data)
summary(data)
```
Colunas
Dar nome correto para as colunas
```{r}
colnames(data) = c("ID", "Score", "State", "Gender", "Age", "Patrimony", "Balance",
 "Products", "CreditCard", "Active", "Salary", "Out")
head(data)
```
Explorar colunas de dados categoricos
```{r}
#States
counts = table(data$State)
barplot(counts, main = "State", xlab = "State")

#gender
counts = table(data$Gender)
barplot(counts, main = "Gender", xlab = "Gender")

```
Explorar colunas numericas

```{r}
#Score
summary(data$Score)
hist(data$Score)

#Age
summary(data$Age)
hist(data$Age)

#Balance
summary(data$Balance)
boxplot(data$Balance)
hist(data$Balance)

#Salary
summary(data$Salary)
boxplot(data$Salary)
boxplot(data$Salary, outline = F)


#missing values - NAs
data[!complete.cases(data),]
```
Processando
```{r}
#Salary
summary(data$Salary)
#ver mediana
median(data$Salary, na.rm = T)
#Na tem agora o valor da mediana
data[is.na(data$Salary),]$Salary = median(data$Salary, na.rm = T)
#checando se ainda exstem dados NA
data[!complete.cases(data$Salary),]
```
Genero
```{r}
#falta de padrão em genero
unique(data$Gender)
summary(data$Gender)
#transformar Fem e Feminino em F e MAsculino em M
data[is.na(data$Gender) | data$Gender == "Masculino",]$Gender = "M"
data[data$Gender == "Fem" | data$Gender == "Feminino",]$Gender = "F"
#ver resultados
summary(data$Gender)
#remover levels não utilizados
data$Gender = factor(data$Gender)
#visualizar denov
summary(data$Gender)
```
Age

```{r}
#Idades fora do dominio
summary(data$Age)
#verificando idades anormais
data[data$Age < 0 | data$Age > 110,]$Age
data[is.na(data$Age)] #Não há idade NA
#opção, preencher com a mediana
median(data$Age)
#substituição
data[data$Age < 0 | data$Age > 110,]$Age = median(data$Age)
#procurar idade anormal de novo
data[data$Age < 0 | data$Age > 110,]$Age    
summary(data$Age)

```
Data

```{r}
#dados duplicados, procurar pelo ID
x = data[duplicated(data$ID),]
x
#pode perceber que o ID 81 está duplicado, então vamos excluir a linha 82
data = data[-c(82),]
#veridicar novamente se existe linhas duplicadas
data[data$ID == x$ID,]
#verificar novamente se está duplicado
x = data[duplicated(data$ID),]
x
```

State

```{r}

#Estado fora do domínio
unique(data$State)
summary(data$State)
#preencher com a Moda -> RS
data[!data$State %in% c ("RS","SC","PR"),]$State = "RS"
summary(data$State)
#remover fatores não usados
data$State = factor(data$State)
summary(data$State)

```

Outliers
```{r}
#outliers, criando parametro com o desvio padrão
std = sd(data$Salary, na.rm = T)
std
data[data$Salary >= 2*std,]$Salary

#outra maneira, resultado similar
boxplot(data$Salary)
boxplot(data$Salary, outline = F)
x = boxplot(data$Salary)$out
x

#atualizar tudo para a mediana
median(data$Salary)
data[data$Salary >= 2*std,]$Salary = median(data$Salary)
#checando se ainda existem outliers
data[data$Salary >= 2*std,]$Salary
boxplot(data$Salary)
```

