Histograma
```{r}
trees
hist( trees$Height)
hist( trees$Height,  main="Trees", ylab="Frequency",xlab="Height", col="blue")
hist( trees$Height,  main="Trees", ylab="Frequency",xlab="Height", col="red",
      density=20, breaks=20    )
```
Densidade
```{r}
dens = density(trees$Height)
plot(dens)
```
Density sobre histograma, por parametro
```{r}
#Executar with ctrl+shift+enter
hist(trees$Height, main=NULL, xlab=NULL, ylab = NULL)
par(new=TRUE)
plot(dens)
```
Dispersão
```{r}
plot(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Volume, main="Trees")
plot(trees$Girth, trees$Volume, ylab="Circumference", xlab="Volume", col="blue", main="Trees")
#pch muda o elemento gráfic
plot(trees$Girth, trees$Volume, ylab="Circumference", xlab="Volume", col="blue", main="Trees", pch=20)
```
Mudar tipo
```{r}
plot(trees$Girth, trees$Volume, ylab="Circumference", xlab="Volume", col="blue", main="Trees", pch=20, type="l")
```
Jitter, reduz sobreposição.
```{r}
plot(jitter(trees$Girth), trees$Volume, ylab="Circumference", xlab="Volume", col="blue", main="Trees")
```
Legenda com dimensão categórica
```{r}
plot(CO2$conc, CO2$uptake,pch=20, col= CO2$Treatment)
#"bottom", "bottomleft", "left", "topleft", "top", "topright", "right" and "center"
legend("bottomright",legend=c("nonchilled","chilled"),cex=1, fill=c("black","red")) 
```
Novos dados
```{r}
plot(trees)
```
Divisão de Tela
```{r}
#Execute with crtl+shift+enter
split.screen(figs=c(2,2))
screen(1)
plot(trees$Girth, trees$Volume)
screen(2)
plot(trees$Girth, trees$Height)
screen(3)
plot(trees$Height, trees$Volume)
screen(4)
hist(trees$Volume)
close.screen(all=TRUE)
```

